accent = "#888888"
cursor = "#FFFFFF"
foreground = "#FFFFFF"
background = "#000000"
selection_foreground = "#000000"
selection_background = "#FFFFFF"
color0 = "#000000"
color1 = "#5F8787"
color2 = "#DD9999"
color3 = "#A06666"
color4 = "#888888"
color5 = "#999999"
color6 = "#AAAAAA"
color7 = "#C1C1C1"
color8 = "#333333"
color9 = "#5F8787"
color10 = "#DD9999"
color11 = "#A06666"
color12 = "#888888"
color13 = "#999999"
color14 = "#AAAAAA"
color15 = "#C1C1C1"
