accent = "#BDBDBD"
cursor = "#FEFEFE"
foreground = "#FEFEFE"
background = "#000000"
selection_foreground = "#FEFEFE"
selection_background = "#2B2B2B"
color0 = "#000000"
color1 = "#FEFEFE"
color2 = "#BDBDBD"
color3 = "#CFCFCF"
color4 = "#BDBDBD"
color5 = "#BDBDBD"
color6 = "#BDBDBD"
color7 = "#FEFEFE"
color8 = "#1A1A1A"
color9 = "#F5F5F5"
color10 = "#BDBDBD"
color11 = "#CFCFCF"
color12 = "#BDBDBD"
color13 = "#BDBDBD"
color14 = "#BDBDBD"
color15 = "#F5F5F5"
