return {
  bg         = "#000000",
  dark_bg    = "#404040",
  darker_bg  = "#404040",
  lighter_bg = "#5c5c5c",

  fg         = "#ffffff",
  dark_fg    = "#a4a4a4",
  light_fg   = "#ececec",
  bright_fg  = "#ffffff",
  muted      = "#cecece",

  red        = "#a4a4a4",
  yellow     = "#cecece",
  orange     = "#9b9b9b",
  green      = "#b6b6b6",
  cyan       = "#b0b0b0",
  blue       = "#8d8d8d",
  purple     = "#9b9b9b",
  brown      = "#a4a4a4",

  bright_red    = "#a4a4a4",
  bright_yellow = "#cecece",
  bright_green  = "#b6b6b6",
  bright_cyan   = "#b0b0b0",
  bright_blue   = "#8d8d8d",
  bright_purple = "#9b9b9b",

  accent               = "#8d8d8d",
  cursor               = "#ffffff",
  foreground           = "#ffffff",
  background           = "#000000",
  selection            = "#5c5c5c",
  selection_foreground = "#000000",
  selection_background = "#ffffff",
}
